### PR TITLE
Better explain benefits of Dogfood.vsix in README.md

### PR DESCRIPTION
**Pull request by ironcev**

### CODE REVIEW

**Review by jcansdale — APPROVED** [review]
If everyone did this, the web would be a better place! 😄

**Comment by ironcev** [comment]
Thanks once again for Dogfood.vsix, Jamie! It liberated me in a way :-) Before I was rarely trying out VS extensions I stumble upon because of the hurdle of restarting all VS instances. Dogfood changed that.

Unfortunately, I didn't dogfood my own extension that often because I was hardly finding time to work on it :-( But this will change in 2019, so I guess Dogfood will become a standard part of my developer arsenal :-)

Since I see a huge value in Dogfood for everyone how wants to play with VS extensions I tried to make the README attractive for all VS users and not only extension developers. This pull request contains my proposal for the README.

**Comment by ironcev** [comment]
BDW, I've noticed a slight naming inconsistency. In the Readme, the extension is called Dogfood.vsix and on VS marketplace Dogfood VSIX ;-) It would be good to go for a unique name. You know, it's important for branding and such stuff :-) And speaking of branding I plan to start talking more about Dogfood in my dev circles. The extension deserves some more visibility :-)

**Comment by jcansdale** [comment]
> I've noticed a slight naming inconsistency. In the Readme, the extension is called Dogfood.vsix and on VS marketplace Dogfood VSIX ;-)

Naming it was a funny one because it's .vsix that helps dogfood .vsix files. 😄 I tried `DigfoodVSIX.vsix`, but that looked strange. I'm happy to keep is consistent as `Digfood.vsix`.

Thanks for your help here. 👍

**Comment by jcansdale** [comment]
It's live!

You can review it here:
https://marketplace.visualstudio.com/items?itemName=JamieCansdale.DogfoodVsix

**Comment by ironcev** [comment]
Yes, the recursive nature of the extension caused me difficulties when I was writing the README. What is "extension" in this sentence, the Dogfood extension itself or the dogfooded extension :-)

**Pull request merged**
